use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::server::auth::signup,
        crate::server::auth::login,
        crate::server::auth::get_profile,
        crate::server::workspaces::create_workspace_handler,
        crate::server::workspaces::list_workspaces_handler,
        crate::server::workspaces::update_workspace_handler,
        crate::server::workspaces::delete_workspace_handler,
        crate::server::workspaces::add_workspace_member_handler,
        crate::server::workspaces::list_workspace_members_handler,
        crate::server::catalog::create_artist_handler,
        crate::server::catalog::list_artists_handler,
        crate::server::catalog::update_artist_handler,
        crate::server::catalog::delete_artist_handler,
        crate::server::catalog::create_album_handler,
        crate::server::catalog::list_albums_handler,
        crate::server::catalog::update_album_handler,
        crate::server::catalog::delete_album_handler,
        crate::server::catalog::create_track_handler,
        crate::server::catalog::list_tracks_handler,
        crate::server::catalog::update_track_handler,
        crate::server::catalog::delete_track_handler,
        crate::server::payees::create_payee_handler,
        crate::server::payees::list_payees_handler,
        crate::server::payees::update_payee_handler,
        crate::server::payees::delete_payee_handler,
        crate::server::splits::create_split_handler,
        crate::server::splits::list_splits_handler,
        crate::server::splits::update_split_handler,
        crate::server::splits::delete_split_handler,
        crate::server::uploads::upload_dataset_direct,
        crate::server::uploads::generate_presigned_url_handler,
        crate::server::uploads::confirm_upload_handler,
        crate::server::uploads::list_datasets_handler,
        crate::server::analytics::execute_query_handler,
        crate::server::analytics::download_query_csv_handler,
        crate::server::analytics::get_analytics_summary_handler,
        crate::server::analytics::get_query_history_handler,
        crate::server::analytics::download_query_history_csv_handler
    ),
    components(
        schemas(
            crate::db::models::UserType,
            crate::db::models::WorkspaceRole,
            crate::db::models::WorkspaceMember,
            crate::db::models::QueryHistoryRecord,
            crate::db::models::User,
            crate::db::models::Workspace,
            crate::db::models::Artist,
            crate::db::models::Album,
            crate::db::models::Track,
            crate::db::models::Payee,
            crate::db::models::CascadingSplit,
            crate::db::models::Dataset,
            crate::db::models::PaginationMeta,
            crate::db::models::PaginationParams,
            crate::server::dtos::auth::RegisterRequest,
            crate::server::dtos::auth::LoginRequest,
            crate::server::dtos::auth::AuthResponse,
            crate::server::dtos::auth::UserInfo,
            crate::server::dtos::workspaces::CreateWorkspaceRequest,
            crate::server::dtos::workspaces::UpdateWorkspaceRequest,
            crate::server::dtos::workspaces::AddWorkspaceMemberRequest,
            crate::server::dtos::common::DeleteResponse,
            crate::server::dtos::common::DatasetResponse,
            crate::server::dtos::catalog::CreateArtistRequest,
            crate::server::dtos::catalog::UpdateArtistRequest,
            crate::server::dtos::catalog::CreateAlbumRequest,
            crate::server::dtos::catalog::UpdateAlbumRequest,
            crate::server::dtos::catalog::CreateTrackRequest,
            crate::server::dtos::catalog::UpdateTrackRequest,
            crate::server::dtos::payees::CreatePayeeRequest,
            crate::server::dtos::payees::UpdatePayeeRequest,
            crate::server::dtos::splits::CreateSplitRequest,
            crate::server::dtos::splits::UpdateSplitRequest,
            crate::server::dtos::uploads::PresignedUrlRequest,
            crate::server::dtos::uploads::PresignedUrlResponse,
            crate::server::dtos::uploads::ConfirmUploadRequest,
            crate::server::dtos::analytics::DateRangeFilter,
            crate::server::dtos::analytics::FilterOperator,
            crate::server::dtos::analytics::QueryFilter,
            crate::server::dtos::analytics::StructuredAnalyticsQuery,
            crate::server::dtos::analytics::AnalyticsQueryRequest,
            crate::server::dtos::analytics::AnalyticsSummaryRequest,
            crate::server::dtos::analytics::AnalyticsQueryResponse,
            crate::server::dtos::analytics::AnalyticsSummaryResponse
        )
    ),
    tags(
        (name = "auth", description = "Authentication and User Profile endpoints"),
        (name = "workspaces", description = "Workspace management and membership endpoints"),
        (name = "catalog", description = "Global user master catalog endpoints (Artists, Albums, Tracks)"),
        (name = "payees", description = "Payee Contact Book endpoints"),
        (name = "splits", description = "Cascading Splits endpoints"),
        (name = "datasets", description = "Dataset Ingestion & Presigned URL endpoints"),
        (name = "analytics", description = "Analytical Engine & Royalty Analytics endpoints")
    )
)]
pub struct ApiDoc;
